version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: gproject-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: gproject
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: gproject-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: 